---
title: "R Notebook"
output: html_notebook
---

```{r}
disease = 'COPD'
test = 'Potassium'
interval = '20'
intervals = read.csv(paste0('medical_data/', interval, '_intervals_', test, '_', disease, '.csv'))
```

```{r}
intervals$constant = rep(1, length(intervals$mean))
```

```{r}
x_given = 4
point = approx(x = intervals$mean, y = intervals$cc_or, xout = x_given)

border_colour = 'black'
point_colour = 'black'
if (point$y > 1) {
  point_colour = 'red'
}
if (point$y > 1 & (point$x < 3.5 | point$x > 5.1)) {
  border_colour = 'red'
} else if (point$y > 1 | (point$x < 3.5 | point$x > 5.1)) {
  border_colour = 'yellow'
}
ggplot(intervals, aes(mean)) + geom_line(aes(y=cc_or), colour='blue') +
  geom_line(aes(y=cc_ci_l, color='cc_ci_l'), linetype='dashed', colour='purple') +
  geom_line(aes(y=cc_ci_r), linetype='dashed', colour='purple') +
  geom_abline(slope=0, intercept=1) + geom_vline(xintercept=3.5, linetype='longdash') +
  geom_vline(xintercept=5.1, linetype='longdash') + coord_cartesian(ylim=c(0,6), xlim=c(2,7)) +
  theme_bw() + geom_point(aes(x=point$x, y=point$y), size=5, color=point_colour) +
  theme(panel.border = element_rect(colour = border_colour, fill=NA, size=5)) +
  labs(x=paste0(test, ', mmol/L'), y='Mortality Odds Ratio', title=paste0(test, ' Odds Ratios +/- 95% C.I. for ', disease))
```





```{r}
sm.add_constant(intervals.set_index('mean')[['cc_or','cc_ci_l','cc_ci_r']]).plot(style=['k-','b-','m:','m:'],
                                                                                 ylim=(0,6), xlim=(2,7), 
                                                                                 figsize=(10, 6))
plt.axvline(3.5, color='black', linestyle='--')
plt.axvline(5.1, color='black', linestyle='--')
plt.legend(('Constant', 'Prediction', 'Confidence Interval'),
           loc='upper right', shadow=True)
plt.xlabel(test + ' , mmol/L')
plt.ylabel('Mortality Odds Ratio')
plt.title(test + ' Odds Ratios +/- 95% C.I. for ' + disease)
plt.show()
```

